### ISSUE TITLE
[BUG] Crash on WLE 1.1.6

### ISSUE THREAD

**Issue by Srile** [playkostudios/gltf-to-wl-bin#2]
When trying to package a .glb file using WLE 1.1.6, a crash occurs during bin compilation (message visible in the image below);

![image](https://github.com/playkostudios/gltf-to-wl-bin/assets/1471367/54e2f523-9ab6-4a35-8b8a-ed1bc5a5ca63)

**Comment by rafern** [comment]
Fixed-ish.

There's 2 ways this tool can convert a model to a .bin file:
- legacy way: manually generate a project file with all the GLTF nodes inside it using gltf-pipeline
- proper way: use Wonderland Engine's `--import` option with a template project

The proper way is used by default if using Wonderland Engine 0.9.5 and above. The proper way was broken in more recent versions, so I fixed it and removed the legacy way (in the `remove-legacy-import` branch). However, even though the editor no longer crashes, it generates empty .bin files.

Because of this, I've force-enabled legacy import as a temporary fix, as well as fixed a bug in legacy import that was affecting recent versions; make sure to update to gltf-to-wl-bin 1.6.2. When Wonderland Engine's `--import` is fixed (or if I figure out that I'm actually using that option incorrectly), I'll switch it to that and do a new release
